name: Build & test (develop)

on:
  push:
    branches:
      - develop

jobs:
  test:
    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.10", "3.11"]
        platform: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{matrix.platform}}

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: 'develop'

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - run: pip install --upgrade pip setuptools wheel
      - run: pip install coverage
      - run: pip install -r requirements.txt

      - name: Run tests with coverage
        run: |
          coverage run --source flowkit --omit="flowkit/tests/*" run_tests.py
          coverage xml

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          files: coverage.xml
          fail_ci_if_error: true
          verbose: true
